name: Maintenance Mode

on:
  schedule:
    - cron: '30 4 * * *' # 11:30 Việt Nam

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Activate maintenance mode
        run: |
          mv index.html index_backup.html
          cp maintenance.html index.html
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Kích hoạt trang bảo trì"
          git push

      - name: Restore main website
        run: |
          sleep 300 # Giữ trang bảo trì trong 5 phút
          mv index_backup.html index.html
          git add index.html
          git commit -m "Khôi phục trang chính sau bảo trì"
          git push
